import { z } from "zod";

export const createComplaintSchema = z.object({
  title: z.string().min(3),
  description: z.string().min(10),
  category: z.string(),
  cinema: z.string().min(24), // ID de ObjectId
  cleaningArea: z.string().optional(),
  cleaningType: z.string().optional(),
  cleaningStaffPresent: z.string().optional(),
  attentionArea: z.string().optional(),
  staffBehavior: z.string().optional(),
  staffDescription: z.string().optional(),
  roomNumber: z.string().optional(),
  technicalIssue: z.string().optional(),
  movieInterrupted: z.string().optional(),
  productAffected: z.string().optional(),
  foodIssue: z.string().optional(),
  purchaseDate: z.string().optional(),
  purchaseLocation: z.string().optional(),
  transactionNumber: z.string().optional(),
  paymentIssue: z.string().optional(),
  infrastructureIssue: z.string().optional(),
  reportedToStaff: z.string().optional(),
  attachEvidence: z.string().optional(),
  securityIncident: z.string().optional(),
  securityIntervention: z.string().optional(),
  physicalRisk: z.string().optional(),
  platform: z.string().optional(),
  appIssue: z.string().optional(),
  appScreenshot: z.string().optional(),
});
