name: Build de backend y frontend

on:
  push:
    branches: [main, dev-pablo]
  pull_request:
    branches: [main, dev-pablo]

jobs:
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar dependencias backend
        run: npm install
      - name: Ejecutar test backend
        run: npm test

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar dependencias frontend
        run: npm install
        working-directory: ./client
      - name: Build frontend
        run: npm run build
        working-directory: ./client
      - name: Ejecutar test frontend
        run: npm test
        working-directory: ./client

  logeo-exitoso:
    name: Logeo exitoso
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - name: Confirmar logeo exitoso
        run: echo "Build y tests exitosos en backend y frontend."

